// Import Prisma Client generated by Prisma
import { PrismaClient } from "@/generated/prisma/client";

import { PrismaPg } from "@prisma/adapter-pg";

// Connect Prisma to PostgreSQL
const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});

// Create the Prisma client
export const prisma = new PrismaClient({ adapter });